/* Main.c file generated by New Project wizard
 *
 * Created:   lun oct 7 2019
 * Processor: PIC18F45K22
 * Compiler:  MPLAB XC8
 */

#include <xc.h>
#define _XTAL_FREQ 8000000
#define PORTA0 PORTAbits.RA0
#define PORTA1 PORTAbits.RA1

#include "config.h"
typedef unsigned char BYTE;
unsigned short ritmo118[4]={254,508,1016,2033}; //{corchea, negra, blanca, redonda} en ms (118 BPM)
BYTE a;
void play_note(BYTE index){
      if(index == 0){
	 
	 PR2 = 239;
	 CCP1CONbits.DC1B = 0b00;
	 CCPR1L = 0b01111000;  //480
      }
      
      else if(index == 1){
	
	 PR2 = 224;
	 CCP1CONbits.DC1B = 0b10;
	 CCPR1L = 0b01110000; //450
      }
      
      else if(index == 2){
	
	 PR2 = 212;
	 CCP1CONbits.DC1B =0b10 ;
	 CCPR1L = 0b01101010;  //426
      }
      
      else if(index == 3){
	 PR2 = 200;
	 CCP1CONbits.DC1B = 0b10;
	 CCPR1L = 0b01100100; //402
      }
      
      else if(index == 4){
	 PR2 = 189;
	 CCP1CONbits.DC1B = 0b00;
	 CCPR1L = 0b01011111;  //380
      }
      
      else if(index == 5){
	 PR2 = 178;
	 CCP1CONbits.DC1B = 0b10;
	 CCPR1L = 0b01011001; //358
      }
      
      else if(index == 6){
	 PR2 = 168;
	 CCP1CONbits.DC1B = 0b10;
	 CCPR1L = 0b01010100;  //338
      }
      
      else if(index == 7){
	 PR2 = 158;
	 CCP1CONbits.DC1B = 0b10;
	 CCPR1L = 0b01001111; //318
      }
      
      else if(index == 8){
	 PR2 = 150;
	 CCP1CONbits.DC1B = 0b10;
	 CCPR1L = 0b01001011;  //302
      }
      
      else if(index == 9){
	 PR2 = 141;
	 CCP1CONbits.DC1B = 00;
	 CCPR1L = 0b01000111; //284
      }
      
      else if(index == 10){
	 PR2 = 133;
	 CCP1CONbits.DC1B = 0b00;
	 CCPR1L = 0b01000011; //268
      }
      
      else{
	 PR2 = 126;
	 CCP1CONbits.DC1B = 0b10;
	 CCPR1L = 0b00111111; //254
      }
}
void ritmo(unsigned short tiempo){ //el tiempo del delay debe ser una constante
   
   if(tiempo == 254)
      __delay_ms(254);
   else if (tiempo == 508)
      __delay_ms(508);
   else if(tiempo == 1016)
      __delay_ms(1016);
   else
      __delay_ms(2033);
    
   
    
}
void silencio_de_corchea(){
   TRISC = 0xFF; //El "Silencio"
   ritmo(ritmo118[0]);
   TRISC = 0x00;
}

void interrupt timer2(void){
   if(PIR1bits.TMR2IF){
      
      PIR1bits.TMR2IF=0;
   }

}




void main(void)
 {
   // Write your code here
   TRISC = 0x00;
   ANSELC = 0;
   PORTC = 0;
   CCPTMRS0bits.C1TSEL = 0;//timer2
   
   T2CONbits.T2CKPS = 0b10;
   
   CCP1CONbits.CCP1M = 0b1100; //pwm mode  ccp1
                 //Se compara
   
   INTCONbits.GIE = 1;    //Global interrupt enable
   PIE1bits.TMR2IE = 1; // TMR2 to PR2 Match
   INTCONbits.PEIE = 1;     //Periferial interrupt enable
   
     
   T2CONbits.TMR2ON = 1; //ON timer 2
   PIR1bits.TMR2IF = 0;
  
   unsigned char cancion[7] = {7, 7, 10, 7, 5, 3, 2};
   unsigned short duracion[7] = {1, 0, 1, 0, 0, 2, 2};
   unsigned char i = 0;

   while(1){
      //cancion: Seven Nation Army(más o menos)BPM 118
      if(i == 7)
	 i = 0;
      
      
      a = cancion[i];
      
      if(i == 1)
	 silencio_de_corchea();
      
      play_note(a);
      ritmo(ritmo118[duracion[i]]);
      
      ++i;
      
   }

 }
